/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./lib/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background:               "#f8f9fa",
        surface:                  "#f8f9fa",
        "surface-bright":         "#f8f9fa",
        "surface-dim":            "#d9dadb",
        "surface-container-lowest":"#ffffff",
        "surface-container-low":  "#f3f4f5",
        "surface-container":      "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest":"#e1e3e4",
        "surface-variant":        "#e1e3e4",
        "on-surface":             "#191c1d",
        "on-surface-variant":     "#44474c",
        "inverse-surface":        "#2e3132",
        "inverse-on-surface":     "#f0f1f2",
        outline:                  "#74777d",
        "outline-variant":        "#c4c6cd",
        primary:                  "#041627",
        "on-primary":             "#ffffff",
        "primary-container":      "#1a2b3c",
        "on-primary-container":   "#8192a7",
        "inverse-primary":        "#b7c8de",
        "primary-fixed":          "#d2e4fb",
        "primary-fixed-dim":      "#b7c8de",
        "on-primary-fixed":       "#0b1d2d",
        "on-primary-fixed-variant":"#38485a",
        secondary:                "#9a442d",
        "on-secondary":           "#ffffff",
        "secondary-container":    "#fc9174",
        "on-secondary-container": "#742814",
        "secondary-fixed":        "#ffdbd2",
        "secondary-fixed-dim":    "#ffb4a1",
        "on-secondary-fixed":     "#3c0800",
        "on-secondary-fixed-variant":"#7c2e19",
        tertiary:                 "#00152e",
        "on-tertiary":            "#ffffff",
        "tertiary-container":     "#002a51",
        "on-tertiary-container":  "#4d93e5",
        "tertiary-fixed":         "#d4e3ff",
        "tertiary-fixed-dim":     "#a4c9ff",
        "on-tertiary-fixed":      "#001c39",
        "on-tertiary-fixed-variant":"#004883",
        error:                    "#ba1a1a",
        "on-error":               "#ffffff",
        "error-container":        "#ffdad6",
        "on-error-container":     "#93000a",
      },
      fontFamily: {
        headline: ['"Source Serif 4"', "Georgia", "serif"],
        body:     ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-xl":        ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg":        ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md":        ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg":            ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":            ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md":           ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        caption:              ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      spacing: {
        "stack-sm":         "8px",
        "stack-md":         "16px",
        "stack-lg":         "32px",
        "section-padding":  "80px",
        "margin-desktop":   "64px",
        "margin-mobile":    "20px",
        gutter:             "24px",
        "container-max":    "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm:  "0.25rem",
        md:  "0.75rem",
        lg:  "1rem",
        xl:  "1.5rem",
      },
      boxShadow: {
        soft: "0 8px 24px rgba(4,22,39,0.08)",
        lift: "0 12px 32px rgba(4,22,39,0.12)",
      },
      keyframes: {
        marquee: {
          "0%":   { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        fadeUp: {
          "0%":   { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%":   { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        marquee: "marquee 35s linear infinite",
        fadeUp:  "fadeUp 0.7s ease forwards",
        shimmer: "shimmer 2s infinite",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
